import { useEffect, useState } from 'react'
import { AlertTriangle, Bell, CarFront, Check, Copy, MapPin, Phone, ShieldCheck, Share2, UserRound, X } from 'lucide-react'
import { api } from '../services/api'
import '../safety.css'

const activeStatuses = ['searching', 'driver_assigned', 'driver_arriving', 'driver_arrived', 'started']
const defaultContacts = []

export default function SafetyCenter({ onBack, onBook, onRides }) {
  const [rides, setRides] = useState([])
  const [contacts, setContacts] = useState(() => JSON.parse(localStorage.getItem('ridex_emergency_contacts') || 'null') || defaultContacts)
  const [preferences, setPreferences] = useState(() => JSON.parse(localStorage.getItem('ridex_safety_preferences') || 'null') || { shareTrip: false, notifications: true, verification: true, pin: true })
  const [modal, setModal] = useState(null)
  const [locationState, setLocationState] = useState('idle')
  const [notice, setNotice] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(true)
  const [form, setForm] = useState({ name: '', relationship: '', phone: '' })

  const load = async () => {
    setLoading(true)
    try { setRides(await api.rides()); setError('') } catch { setError("We couldn't load your safety information right now.") } finally { setLoading(false) }
  }
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer) }, [])
  useEffect(() => { localStorage.setItem('ridex_emergency_contacts', JSON.stringify(contacts)) }, [contacts])
  useEffect(() => { localStorage.setItem('ridex_safety_preferences', JSON.stringify(preferences)) }, [preferences])
  useEffect(() => { if (!modal) return undefined; const close = (event) => event.key === 'Escape' && setModal(null); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [modal])

  const activeRide = rides.find((ride) => activeStatuses.includes(ride.status))
  const updatePreference = (key) => setPreferences((current) => ({ ...current, [key]: !current[key] }))
  const captureLocation = () => { if (!navigator.geolocation) return setLocationState('unavailable'); setLocationState('loading'); navigator.geolocation.getCurrentPosition(() => setLocationState('ready'), () => setLocationState('denied'), { enableHighAccuracy: true, timeout: 8000 }) }
  const tripText = activeRide ? `RideX trip ${activeRide._id}\n${activeRide.pickup} to ${activeRide.destination}\nStatus: ${activeRide.status}\nDriver and vehicle details are available in the RideX app.` : ''
  const shareTrip = async () => { if (!activeRide) return setNotice('There is no active ride to share.'); try { if (navigator.share) await navigator.share({ title: 'My RideX trip', text: tripText }); else { await navigator.clipboard.writeText(tripText); setNotice('Trip details copied to clipboard.') } } catch (shareError) { if (shareError.name !== 'AbortError') setNotice('Trip sharing was cancelled or unavailable.') } }
  const saveContact = (event) => { event.preventDefault(); if (contacts.length >= 2) return setError('You can add a maximum of 2 emergency contacts.'); if (!form.name.trim() || !form.relationship.trim() || !/^\+?[0-9 ()-]{7,}$/.test(form.phone)) return setError('Enter a name, relationship, and valid phone number.'); if (contacts.some((contact) => contact.phone === form.phone)) return setError('This emergency contact is already saved.'); setContacts((current) => [...current, { ...form, id: crypto.randomUUID() }]); setForm({ name: '', relationship: '', phone: '' }); setModal(null); setNotice('Emergency contact saved on this device.') }
  const call = (phone) => { if (/^\+?[0-9 ()-]{7,}$/.test(phone)) window.open(`tel:${phone.replace(/[^0-9+]/g, '')}`, '_self'); else setError('This contact does not have a valid phone number.') }

  return <div className="workspace-view safety-center">
    <button className="back-link" onClick={onBack}>← Back to overview</button>
    <div className="safety-heading"><div><p className="section-kicker">RIDE PROTECTION</p><h1>Safety Center</h1><p className="subheading">Your safety comes first. Get help, share your trip, and manage ride safety from one place.</p></div><div className="safety-status"><ShieldCheck size={18} /><span>{activeRide ? 'Active ride' : 'Safety tools ready'}</span><small>{activeRide ? "You're currently on a ride" : 'No active ride'}</small></div></div>
    {error && <div className="safety-alert" role="alert">{error}<button aria-label="Dismiss error" onClick={() => setError('')}><X size={14} /></button></div>}{notice && <div className="safety-notice" role="status">{notice}<button aria-label="Dismiss notice" onClick={() => setNotice('')}><X size={14} /></button></div>}
    <section className="safety-active"><div><p className="section-kicker">{activeRide ? 'YOUR ACTIVE RIDE' : 'SAFETY STATUS'}</p><h2>{activeRide ? `${activeRide.category} ride` : 'You do not have an active ride right now.'}</h2><p>{activeRide ? `${activeRide.pickup} → ${activeRide.destination} · ${activeRide.status}` : 'Your safety tools remain available whenever you need them.'}</p></div><div className="safety-actions">{activeRide ? <><button onClick={() => onRides(activeRide)}><MapPin size={15} /> Track Ride</button><button onClick={() => setModal('share')}><Share2 size={15} /> Share Trip</button><button onClick={() => setModal('sos')} className="sos-button"><AlertTriangle size={15} /> Emergency SOS</button></> : <><button onClick={onBook}>Book a Ride</button><button onClick={onRides}>View My Rides</button></>}</div></section>
    <div className="safety-grid"><section className="safety-card"><div className="safety-card-title"><div><p className="section-kicker">TRUSTED PEOPLE</p><h2>Emergency Contacts</h2></div><button disabled={contacts.length >= 2} onClick={() => setModal('contact')} aria-label="Add emergency contact">+ Add</button></div>{contacts.length ? contacts.map((contact) => <div className="contact-row" key={contact.id}><div className="contact-avatar"><UserRound size={16} /></div><div><strong>{contact.name}</strong><small>{contact.relationship} · {contact.phone.replace(/.(?=.{4})/g, '•')}</small></div><button onClick={() => call(contact.phone)} aria-label={`Call ${contact.name}`}><Phone size={15} /></button><button onClick={() => setContacts((current) => current.filter((item) => item.id !== contact.id))} aria-label={`Delete ${contact.name}`}><X size={15} /></button></div>) : <p className="empty-state">No trusted contacts saved yet.</p>}{contacts.length < 2 && <button className="safety-link" onClick={() => setModal('contact')}>+ Add Emergency Contact</button>}</section>
      <section className="safety-card"><div className="safety-card-title"><div><p className="section-kicker">TRIP VISIBILITY</p><h2>Share Live Trip</h2></div><Share2 size={18} /></div><p>Share your current ride details through your device's secure sharing options.</p><button className="primary-button" onClick={shareTrip} disabled={!activeRide}><Share2 size={15} /> Share Ride Details</button>{activeRide && <button className="safety-link" onClick={() => setModal('share')}>View trip details</button>}</section></div>
    <div className="safety-grid"><section className="safety-card"><div className="safety-card-title"><div><p className="section-kicker">SAFETY TOOLS</p><h2>Driver &amp; Vehicle Details</h2></div><CarFront size={18} /></div>{activeRide?.driver ? <p>Assigned driver details are available on the live ride screen.</p> : <p className="empty-state">Verification information unavailable until a driver is assigned.</p>}{activeRide ? <button className="safety-link" onClick={() => onRides(activeRide)}>Open live ride</button> : null}</section><section className="safety-card"><div className="safety-card-title"><div><p className="section-kicker">RIDE VERIFICATION</p><h2>Ride PIN</h2></div><ShieldCheck size={18} /></div><p>Share your Ride PIN only with the assigned driver. It is hidden until an active ride is available.</p>{activeRide?.ridePin && <button className="safety-link" onClick={() => setModal('pin')}>Show and copy PIN</button>}</section></div>
    <section className="safety-card safety-preferences"><div className="safety-card-title"><div><p className="section-kicker">YOUR SETTINGS</p><h2>Safety Preferences</h2></div><Bell size={18} /></div>{[['shareTrip', 'Automatically share my trip', 'Share ride details with selected trusted contacts when a trip starts.'], ['notifications', 'Safety notifications', 'Receive important ride and safety updates.'], ['verification', 'Driver verification reminders', 'Remind me to check driver and vehicle details.'], ['pin', 'Ride PIN reminders', 'Remind me to verify the driver before sharing the PIN.']].map(([key, label, description]) => <button className="preference-row" key={key} onClick={() => updatePreference(key)}><span><strong>{label}</strong><small>{description}</small></span><b className={preferences[key] ? 'toggle on' : 'toggle'} aria-label={`${label}: ${preferences[key] ? 'On' : 'Off'}`}></b></button>)}</section>
    <div className="safety-grid"><section className="safety-card"><div className="safety-card-title"><div><p className="section-kicker">RIDE SUPPORT</p><h2>Report an issue</h2></div><AlertTriangle size={18} /></div><p>Support reports are not connected to a backend endpoint yet. No report was submitted.</p><button className="primary-button" onClick={() => setModal('report')}>Report a Problem</button><button className="safety-link" onClick={() => setModal('report')}>Report Unsafe Behavior</button><button className="safety-link" onClick={() => setModal('report')}>Report Lost Item</button></section><section className="safety-card"><div className="safety-card-title"><div><p className="section-kicker">BEFORE YOU RIDE</p><h2>Safety Tips</h2></div><Check size={18} /></div><ul className="safety-tips"><li>Check the driver name, photo, and registration number.</li><li>Confirm your pickup location and keep your phone charged.</li><li>Never share your OTP or PIN before verification.</li><li>Keep trusted contacts informed during your ride.</li></ul></section></div>
    {loading && <p className="loading-state">Loading your ride safety information...</p>}
    {modal && <SafetyModal type={modal} activeRide={activeRide} form={form} setForm={setForm} onClose={() => setModal(null)} onSOS={captureLocation} locationState={locationState} onShare={shareTrip} onSaveContact={saveContact} onCall={call} />}
  </div>
}

function SafetyModal({ type, activeRide, form, setForm, onClose, onSOS, locationState, onShare, onSaveContact, onCall }) {
  const title = type === 'sos' ? 'Emergency SOS' : type === 'share' ? 'Share Live Trip' : type === 'contact' ? 'Add Emergency Contact' : type === 'pin' ? 'Ride Verification PIN' : 'Ride Support'
  return <div className="support-dialog-backdrop" role="presentation" onClick={onClose}><section className={`support-dialog safety-modal ${type === 'sos' ? 'sos-modal' : ''}`} role="dialog" aria-modal="true" aria-labelledby="safety-modal-title" onClick={(event) => event.stopPropagation()}><button className="dialog-close" aria-label={`Close ${title}`} onClick={onClose}><X size={16} /></button><p className="section-kicker">RIDEX SAFETY</p><h2 id="safety-modal-title">{title}</h2>{type === 'sos' && <><p>Are you sure you want to activate Emergency SOS?</p><p className="safety-warning">Emergency services integration is not configured. Please contact local emergency services directly.</p><button className="primary-button" onClick={onSOS}><AlertTriangle size={15} /> Capture location</button>{locationState !== 'idle' && <small className="modal-status">{locationState === 'ready' ? 'Location permission granted for this action.' : locationState === 'denied' ? 'Location access is disabled. Enable location access to use location-based safety features.' : locationState === 'loading' ? 'Requesting location permission...' : 'Location is unavailable in this browser.'}</small>}<button className="safety-link" onClick={onCall.bind(null, '')}>Contact local emergency services</button></>}{type === 'share' && <><p>{activeRide ? `${activeRide.pickup} → ${activeRide.destination}` : 'No active ride.'}</p><small>Ride ID: {activeRide?._id || 'Unavailable'} · Status: {activeRide?.status || 'Unavailable'}</small><button className="primary-button" onClick={onShare}><Share2 size={15} /> Share or copy details</button></>}{type === 'contact' && <form className="safety-form" onSubmit={onSaveContact}><label>Name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Relationship<input required value={form.relationship} onChange={(event) => setForm({ ...form, relationship: event.target.value })} /></label><label>Phone number<input required type="tel" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label><button className="primary-button" type="submit">Save contact</button></form>}{type === 'pin' && <><p>Share your Ride PIN only with the assigned driver.</p><strong className="ride-pin">{activeRide?.ridePin || 'Unavailable'}</strong><button className="primary-button" onClick={() => navigator.clipboard.writeText(activeRide.ridePin)}>Copy PIN <Copy size={15} /></button></>}{type === 'report' && <><p>Support report submission is unavailable because no backend report endpoint is configured.</p><button className="primary-button" onClick={onClose}>Contact support instead</button></>}</section></div>
}
